/*
 * Copyright (c) 2020 Anton Bagdatyev (Tonix)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use,
 * copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following
 * conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 */

import { packagePath, walkSync, basenameWithoutExtension } from "node-utl";
import { writeFileSync } from "fs";

/**
 * @type {string}
 */
const RES_FOLDER_PATH = `${__dirname}/../../res`; // The script executes from within the ./dist/bin directory.

/**
 * Creates a resource file for all the supported locales of the Moment library.
 *
 * @return {undefined}
 * @throws {Error} If the "node_modules/moment/locale" directory is not found.
 */
export default function createAllSupportedLocalesRes() {
  const momentPackagePath = packagePath("moment");
  const localesPath = `${momentPackagePath}/locale`;
  const allSupportedLocalesAbsoluteFilenames = walkSync(localesPath);
  const locales = allSupportedLocalesAbsoluteFilenames
    .map(basenameWithoutExtension)
    .sort();
  let id = 1;
  const localesCode = `/*
 * Copyright (c) 2020 Anton Bagdatyev (Tonix)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use,
 * copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following
 * conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 */

/**
 * This file is automatically generated by this package or when running "npx moment-utl-locales".
 */

/**
 * @type {string[]}
 */
const allSupportedLocales = ${JSON.stringify(locales)};

/**
 * @type {Object}
 */
const allSupportedLocalesObj = ${JSON.stringify(
    locales.reduce((carry, current) => ({ ...carry, [current]: id++ }), {})
  )};

export { allSupportedLocales, allSupportedLocalesObj };
`;
  writeFileSync(`${RES_FOLDER_PATH}/locales.js`, localesCode);
}
